package vn.com.mta.science.util;

public enum ItechAuthority {
    SYSADMIN,
    USER_GET_ALL,
    USER_GET,
    USER_ADD,
    USER_EDIT,
    USER_DELETE,

    DOCUMENT_GET,
    DOCUMENT_ADD,
    DOCUMENT_EDIT,
    DOCUMENT_DELETE,


    GROUP_GET,
    GROUP_EDIT,
    GROUP_ADD,
    GROUP_DELETE,

    AUTHOR_GET,
    AUTHOR_EDIT,
    AUTHOR_ADD,
    AUTHOR_DELETE,

    INVENTION_GET,
    INVENTION_ADD,
    INVENTION_EDIT,
    INVENTION_DELETE,

    AFFILIATION_GET,
    AFFILIATION_EDIT,
    AFFILIATION_ADD,
    AFFILIATION_DELETE,

    CLASSIFICATION_GET,
    CLASSIFICATION_ADD,
    CLASSIFICATION_EDIT,
    CLASSIFICATION_DELETE,

    DOCUMENTTYPE_GET,
    DOCUMENTTYPE_EDIT,
    DOCUMENTTYPE_ADD,
    DOCUMENTTYPE_DELETE,

    LANGUAGE_GET,
    LANGUAGE_ADD,
    LANGUAGE_EDIT,
    LANGUAGE_DELETE,

    DEGREE_GET,
    DEGREE_ADD,
    DEGREE_EDIT,
    DEGREE_DELTE,

    MAJOR_GET,
    MAJOR_EDIT,
    MAJOR_ADD,
    MAJOR_DELETE,

    CITED_GET,
    CITED_ADD,
    CITED_EDIT,
    CITED_DELETE,

}
